<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Vtdc' => '',
  'Vtdc Deleted' => 'Deleted',
  'Vtdc Expire Date' => 'Expire Date',
  'Vtdc Issue Date' => 'Issue Date',
  'Vtdc Notes' => 'Notes',
  'Vtdc Number' => 'Number',
  'Vtdc Truck Doc' => 'Truck documents',
  'Vtdc Updated' => 'Updated',
  'Vtdc Vtdt' => '',
  'Vtdc Vtrc' => '',
  'Vtdt' => '',
  'Vtdt Hidded' => 'Hidded',
  'Vtdt Name' => 'Name',
  'Vtdt Truck Doc Type' => 'Document type',
  'Vtdt Truck Doc Types' => 'Document types',
  'Vtrc' => '',
  'Vtrc Car Certificate Number' => 'Car Certificate Number',
  'Vtrc Car Reg Nr' => 'Car Reg Nr',
  'Vtrc Cmmp' => 'Company',
  'Vtrc Fuel Consumption' => 'Fuel Consumption',
  'Vtrc Leased From Cmmp' => 'Leased From',
  'Vtrc Notes' => 'Notes',
  'Vtrc Purchase Value' => 'Purchase Value',
  'Vtrc Self Weight' => 'Self Weight',
  'Vtrc Truck' => 'Truck',
  'Vtrc Trucks' => 'Trucks',
  'Vtrc Year' => 'Year',
  'Vtrc Year Mileage' => 'Year/Km',
  'relation.VtdcTruckDocs' => '',
  'tooltip.vtdt_hidded' => '',
  'tooltip.vtdt_id' => '',
  'tooltip.vtdt_name' => '',
  'tooltip.vtrc_car_certificate_number' => '',
  'tooltip.vtrc_car_reg_nr' => '',
  'tooltip.vtrc_fuel_consumption' => '',
  'tooltip.vtrc_id' => '',
  'tooltip.vtrc_leased_from_cmmp_id' => '',
  'tooltip.vtrc_notes' => '',
  'tooltip.vtrc_purchase_value' => '',
  'tooltip.vtrc_self_weight' => '',
  'tooltip.vtrc_year' => '',
  'tooltip.vtrc_year_mileage' => '',
);
