<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Atcelt',
  'Create' => 'Izveidot',
  'Delete' => 'Dzēst',
  'Do you want to delete this item?' => 'Vai patiešam vēlaties šo ierakstu dzēst',
  'Fields with <span class="required">*</span> are required.' => 'Atzīmētie ar <span class="required">*</span> ir obligāti.',
  'Invalid request. Please do not repeat this request again.' => 'Kļūdains pieprasījums.',
  'Manage' => 'Saraksts',
  'Relations' => 'Relācijas',
  'Save' => 'Saglabāt',
  'Search' => 'Meklēt',
  'The requested page does not exist.' => 'Pieprasītā lapa neeksistē',
  'Update' => 'Labot',
  'View' => 'Skatīt',
);
